### ISSUE TITLE
Mod log

### ISSUE THREAD

**Issue by spotlightishere** [RiiConnect24/RC24-Bot#8]
Currently, on servers without a mod log, we get the following:
```
[ERROR : et-14417 @ 2017-03-26 23:02:57.454] Exception: #<NoMethodError: undefined method `resolve_id' for nil:NilClass>
[ERROR : et-14417 @ 2017-03-26 23:02:57.454] /home/spotlight/gems/ruby/2.4.0/gems/discordrb-3.2.1/lib/discordrb/cache.rb:33:in `channel'
[ERROR : et-14417 @ 2017-03-26 23:02:57.454] /home/spotlight/RC24-Bot/modules/userjoin.rb:13:in `get_mod_log?'
[ERROR : et-14417 @ 2017-03-26 23:02:57.454] /home/spotlight/RC24-Bot/modules/userjoin.rb:89:in `block in <module:Userjoin>'
[ERROR : et-14417 @ 2017-03-26 23:02:57.454] /home/spotlight/gems/ruby/2.4.0/gems/discordrb-3.2.1/lib/discordrb/events/generic.rb:98:in `call'
[ERROR : et-14417 @ 2017-03-26 23:02:57.454] /home/spotlight/gems/ruby/2.4.0/gems/discordrb-3.2.1/lib/discordrb/bot.rb:1227:in `block in call_event'
```

A check should be added. I don't have enough time to do it myself.

**Comment by awesomebing1** [comment]
It be noted that this is due to the server at one point having a log, but the channel was deleted. Locally I ave a change implemented, I'll have to push it later along with some other logging state stuff I have set up.

**Comment by joscomputing** [comment]
Fixed, somewhere that I don't even remember lol but it went in with all of the log reformatting
